# 服务配置
server:
  # 服务端口
  port: 8080
  # 服务模式 (development/production)
  mode: development

# 数据库配置
database:
  driver: sqlite3
  source: storage/data/digital_currency.db

# 区块链配置
blockchain:
  # 区块生成间隔(秒)
  block_interval: 60
  # 初始难度值

# 日志配置
log:
  # 日志级别 (debug/info/warn/error)
  level: debug
  # 日志文件路径
  file: storage/logs/app.log
  # 是否输出到控制台
  console: true
  # 日志轮转配置
  rotation:
    # 最大大小(MB)
    max_size: 100
    # 保留天数
    max_age: 30
    # 保留文件数
    max_backups: 10
    
Tron:
  Enable: 1
  ApiKey:
  Node: https://api.trongrid.io
  Contract:
    - Token: USDT
      Address: 41a614f803b6fd780986a42c78ec9c7f77e6ded13c
      Decimal: 6
